INSERT INTO mounts
(mount_name, mount_description, mount_picture)
VALUES
-- ('Adamantoise', '200,000 MGP', 'https://ffxiv.gamerescape.com/w/images/8/87/Adamantoise_%28Mount%29_Icon.png'),
-- ('Aerodynamics System', 'In A Blaze Of Glory V', 'https://ffxiv.gamerescape.com/w/images/c/c2/Aerodynamics_System_%28Mount%29_Icon.png'),
-- ('Ahriman', 'Jonathas - Old Gridania - 6 Achievement Certificates', 'https://ffxiv.gamerescape.com/w/images/0/03/Ahriman_%28Mount%29_Icon.png'),
('Air Force', 'Sigmascape V4.0 (Savage)', 'https://ffxiv.gamerescape.com/w/images/5/56/Air_Force_%28Mount%29_Icon.png'),
('Aithon', 'Bowl of Embers (Extreme)', 'https://ffxiv.gamerescape.com/w/images/6/60/Aithon_%28Mount%29_Icon.png'),
('Albino Karakul', '8,400 Skybuilders'' Scrips', 'https://ffxiv.gamerescape.com/w/images/9/9d/Albino_Karakul_%28Mount%29_Icon.png'),
('Alte Roite', 'Deltascape V4.0 (Savage)', 'https://ffxiv.gamerescape.com/w/images/7/7d/Alte_Roite_%28Mount%29_Icon.png'),
('Amaro', 'A Life of Adventure IV', 'https://ffxiv.gamerescape.com/w/images/c/c8/Amaro_%28Mount%29_Icon.png'),
('Amber Draught Chocobo', 'Calamity Salvager - 8 Gold Chocobo Feathers (Recruit a Friend Campaign)', 'https://ffxiv.gamerescape.com/w/images/4/42/Amber_Draught_Chocobo_%28Mount%29_Icon.png'),
('Aquamarine Carbuncle', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/e/e4/Aquamarine_Carbuncle_%28Mount%29_Icon.png'),
('Archon Throne', '750,000 MGP', 'https://ffxiv.gamerescape.com/w/images/4/4d/Archon_Throne_%28Mount%29_Icon.png'),
('Arrhideaus', 'Alexander - The Soul Of The Creator (Savage)', 'https://ffxiv.gamerescape.com/w/images/0/01/Arrhidaeus_%28Mount%29_Icon.png'),
('Auspicious Kamuy', 'The Jade Stoa (Extreme)', 'https://ffxiv.gamerescape.com/w/images/d/d1/Auspicious_Kamuy_%28Mount%29_Icon.png'),
('Battle Bear', 'Tank You, Warrior III', 'https://ffxiv.gamerescape.com/w/images/d/db/Battle_Bear_%28Mount%29_Icon.png'),
('Battle Lion', 'Tank You, Paladin III', 'https://ffxiv.gamerescape.com/w/images/a/a6/Battle_Lion_%28Mount%29_Icon.png'),
('Battle Panther', 'Tank You, Dark Knight III', 'https://ffxiv.gamerescape.com/w/images/7/73/Battle_Panther_%28Mount%29_Icon.png'),
('Battle Tiger', 'Tank You, Gunbreaker III', 'https://ffxiv.gamerescape.com/w/images/3/3c/Battle_Tiger_%28Mount%29_Icon.png'),
('Behemoth', 'Jonathas - Old Gridania - 6 Achievement Certificates', 'https://ffxiv.gamerescape.com/w/images/a/a6/Behemoth_%28Mount%29_Icon.png'),
('Bennu', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/3/37/Bennu_%28Mount%29_Icon.png'),
('Big Shell', '8,400 Skybuilders'' Scrips', 'https://ffxiv.gamerescape.com/w/images/d/d7/Big_Shell_%28Mount%29_Icon.png'),
('Black Chocobo', 'Divine Intervention', 'https://ffxiv.gamerescape.com/w/images/3/3d/Black_Chocobo_%28Mount%29_Icon.png'),
('Black Pegasus', 'Palace of The Dead', 'https://ffxiv.gamerescape.com/w/images/f/f3/Black_Pegasus_%28Mount%29_Icon.png'),
('Blissful Kamuy', 'Emanation (Extreme)', 'https://ffxiv.gamerescape.com/w/images/1/1e/Blissful_Kamuy_%28Mount%29_Icon.png'),
('Bomb Palanquin', 'Kobold Vendor - 789th Order Dig - 120,000 Gil', 'https://ffxiv.gamerescape.com/w/images/c/c4/Bomb_Palanquin_%28Mount%29_Icon.png'),
('Boreas', 'Akh Afah Amphitheatre (Extreme)', 'https://ffxiv.gamerescape.com/w/images/7/71/Boreas_%28Mount%29_Icon.png'),
('Broken Heart (Left)', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/3/3c/Broken_Heart_%28Left%29_%28Mount%29_Icon.png'),
('Broken Heart (Right)', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/e/e8/Broken_Heart_%28Right%29_%28Mount%29_Icon.png'),
('Cavalry Drake', 'Amalj''aa Vendor - Ring of Ash - 120,000 Gil', 'https://ffxiv.gamerescape.com/w/images/4/41/Cavalry_Drake_%28Mount%29_Icon.png'),
('Cavalry Elbst', 'Sahagin Vendor - Novv''s Nursery - 120,000 Gil', 'https://ffxiv.gamerescape.com/w/images/4/45/Cavalry_Elbst_%28Mount%29_Icon.png'),
('Centurio Tiger', 'You Got Game', 'https://ffxiv.gamerescape.com/w/images/b/b5/Centurio_Tiger_%28Mount%29_Icon.png'),
('Chocorpokkur', 'Butterfinger Promotion (NA Only)', 'https://ffxiv.gamerescape.com/w/images/0/0f/Chocorpokkur_%28Mount%29_Icon.png'),
('Circus Ahriman', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/4/47/Circus_Ahriman_%28Mount%29_Icon.png'),
('Citrine Carbuncle', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/4/4d/Citrine_Carbuncle_%28Mount%29_Icon.png'),
('Cloud Mallow', 'Mogmul Mogbelly - Bahrr Lehs - 200,000 Gil', 'https://ffxiv.gamerescape.com/w/images/1/12/Cloud_Mallow_%28Mount%29_Icon.png'),
('Coeurl', 'A Realm Reborn Collectors'' Edition', 'https://ffxiv.gamerescape.com/w/images/f/fe/Coeurl_%28Mount%29_Icon.png'),
('Company Chocobo', 'My Little Chocobo', 'https://ffxiv.gamerescape.com/w/images/7/77/Company_Chocobo_%28Mount%29_Icon.png'),
('Construct 14', '180 Bozjan Clusters', 'https://ffxiv.gamerescape.com/w/images/8/84/Construct_14_%28Mount%29_Icon.png'),
('Construct VI-S', '600 Faux Leaves', 'https://ffxiv.gamerescape.com/w/images/4/47/Construct_VI-S_%28Mount%29_Icon.png'),
('Construct VII', 'One Steppe at a Time V', 'https://ffxiv.gamerescape.com/w/images/b/b7/Construct_VII_%28Mount%29_Icon.png'),
('Dark Lanner', 'The Minstrel''s Ballad: Nidhogg''s Rage', 'https://ffxiv.gamerescape.com/w/images/4/48/Dark_Lanner_%28Mount%29_Icon.png'),
('Demi-Ozma', 'We''re on Your Side I', 'https://ffxiv.gamerescape.com/w/images/e/ea/Demi-Ozma_%28Mount%29_Icon.png'),
('Demonic Lanner', 'Containment Bay Z1T9 (Extreme)', 'https://ffxiv.gamerescape.com/w/images/8/89/Demonic_Lanner_%28Mount%29_Icon.png'),
('Dhalmel', 'Kupo of Fortune', 'https://ffxiv.gamerescape.com/w/images/6/6d/Dhalmel_%28Mount%29_Icon.png'),
('Direwolf', 'Ixali Vendor - Ehcatl - 120,000 Gil', 'https://ffxiv.gamerescape.com/w/images/0/03/Direwolf_%28Mount%29_Icon.png'),
('Disembodied Head', 'E-Una-Kotor - Quarrymill - 10 Gelmorran Potsherds', 'https://ffxiv.gamerescape.com/w/images/2/27/Disembodied_Head_%28Mount%29_Icon.png'),
('Dodo', 'Heaven-on-High', 'https://ffxiv.gamerescape.com/w/images/d/da/Dodo_%28Mount%29_Icon.png'),
('Diamond Gwiber', 'The Cloud Deck (Extreme)', 'https://ffxiv.gamerescape.com/w/images/f/f4/Diamond_Gwiber_%28Mount%29_Icon.png'),
('Eden', 'Eden''s Promise: Eternity (Savage)', 'https://ffxiv.gamerescape.com/w/images/5/5a/Eden_%28Mount%29_Icon.png'),
('Eggshilaration System', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/a/a2/Eggshilaration_System_%28Mount%29_Icon.png'),
('Ehll Tou', 'On Ehll Tou''s Wings', 'https://ffxiv.gamerescape.com/w/images/e/e8/Ehll_Tou_%28Mount%29_Icon.png'),
('Eldthurs', 'Happy Bunny Lockbox - Eureka Pyros', 'https://ffxiv.gamerescape.com/w/images/5/5f/Eldthurs_%28Mount%29_Icon.png'),
('Emerald Gwibber', 'Castrum Marinum (Extreme)', 'https://ffxiv.gamerescape.com/w/images/5/55/Emerald_Gwiber_%28Mount%29_Icon.png'),
('Enbarr', 'The Whorleater (Extreme)', 'https://ffxiv.gamerescape.com/w/images/7/7c/Enbarr_%28Mount%29_Icon.png'),
('Epimetheus', 'The Feast: Season 14', 'https://ffxiv.gamerescape.com/w/images/8/82/Epimetheus_%28Mount%29_Icon.png'),
('Euphonious Kamuy', 'Hells'' Kier (Extreme)', 'https://ffxiv.gamerescape.com/w/images/9/9e/Euphonious_Kamuy_%28Mount%29_Icon.png'),
('Eurekan Petrel', 'Happy Bunny Lockbox - Eureka Hydatos', 'https://ffxiv.gamerescape.com/w/images/3/34/Eurekan_Petrel_%28Mount%29_Icon.png'),
('Fae Gwibber', 'The Dancing Plague (Extreme)', 'https://ffxiv.gamerescape.com/w/images/b/b0/Fae_Gwiber_%28Mount%29_Icon.png'),
('Falcon', 'Fly the Falcon Mount Campaign', 'https://ffxiv.gamerescape.com/w/images/0/08/Falcon_%28Mount%29_Icon.png'),
('Fat Black Chocobo', 'In-Game Item Campaign', 'https://ffxiv.gamerescape.com/w/images/c/c4/Fat_Black_Chocobo_%28Mount%29_Icon.png'),
('Fat Chocobo', 'A Realm Reborn Collector''s Edition', 'https://ffxiv.gamerescape.com/w/images/3/39/Fat_Chocobo_%28Mount%29_Icon.png'),
('Fatter Cat', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/6/60/Fatter_Cat_%28Mount%29_Icon.png'),
('Fenrir', '1,000,000 MGP', 'https://ffxiv.gamerescape.com/w/images/3/31/Fenrir_%28Mount%29_Icon.png'),
('Firebird', 'Fiery Wings, Fiery Heart', 'https://ffxiv.gamerescape.com/w/images/7/77/Firebird_%28Mount%29_Icon.png'),
('Flame Warstead', 'A Line in the Sand IV', 'https://ffxiv.gamerescape.com/w/images/1/15/Flame_Warsteed_%28Mount%29_Icon.png'),
('Flying Chair', 'Crafted by Alchemist', 'https://ffxiv.gamerescape.com/w/images/f/f8/Flying_Chair_%28Mount%29_Icon.png'),
('Flying Cumulus', 'In-Game Item Campaign', 'https://ffxiv.gamerescape.com/w/images/7/76/Flying_Cumulus_%28Mount%29_Icon.png'),
('Forgiven Reticence', '3,200 Sacks of Nuts', 'https://ffxiv.gamerescape.com/w/images/4/40/Forgiven_Reticence_%28Mount%29_Icon.png'),
('Gabriel Mark III', 'Delubrum Reginae', 'https://ffxiv.gamerescape.com/w/images/3/32/Gabriel_Mark_III_%28Mount%29_Icon.png'),
('Gabriel A', 'Southern Front Lockbox', 'https://ffxiv.gamerescape.com/w/images/8/8f/Gabriel_%CE%B1_%28Mount%29_Icon.png'),
('Gilded Magitek Armor', 'Everybody''s Darling', 'https://ffxiv.gamerescape.com/w/images/e/e7/Gilded_Magitek_Armor_%28Mount%29_Icon.png'),
('Gilded Mikoshi', 'Edelina - Mor Dhona - 50,000,000 Gil', 'https://ffxiv.gamerescape.com/w/images/8/80/Gilded_Mikoshi_%28Mount%29_Icon.png'),
('Ginga', 'Frontline Fury', 'https://ffxiv.gamerescape.com/w/images/5/56/Ginga_%28Mount%29_Icon.png'),
('Gloria-class Airship', 'You Are What You Eat IV', 'https://ffxiv.gamerescape.com/w/images/9/9b/Gloria-class_Airship_%28Mount%29_Icon.png'),
('Gobwalker', 'Alexander - The Burden of the Father (Savage)', 'https://ffxiv.gamerescape.com/w/images/e/e5/Gobwalker_%28Mount%29_Icon.png'),
('Goobbue', 'At Level 30 or Above Speak with the Wandering Minstrel', 'https://ffxiv.gamerescape.com/w/images/2/2d/Goobbue_%28Mount%29_Icon.png'),
('Goten', 'Fatal Feast', 'https://ffxiv.gamerescape.com/w/images/6/6c/Goten_%28Mount%29_Icon.png'),
('Grani', 'Shadowbringers Collectors'' Edition', 'https://ffxiv.gamerescape.com/w/images/4/45/Grani_%28Mount%29_Icon.png'),
('Great Vessel Of Ronka', 'Yuqurl Manl - The Rak''tika Greatwood - 18 Qitari Compliments', 'https://ffxiv.gamerescape.com/w/images/b/bb/Great_Vessel_of_Ronka_%28Mount%29_Icon.png'),
('Griffin', 'Heavensward Collectors'' Edition', 'https://ffxiv.gamerescape.com/w/images/2/21/Griffin_%28Mount%29_Icon.png'),
('Gullfaxi', 'The Navel (Extreme)', 'https://ffxiv.gamerescape.com/w/images/e/ec/Gullfaxi_%28Mount%29_Icon.png'),
('Gwiber of Light', 'The Seat of Sacrifice (Extreme)', 'https://ffxiv.gamerescape.com/w/images/8/8f/Gwiber_of_Light_%28Mount%29_Icon.png'),
('Hallowed Kamuy', 'The Wreath of Snakes (Extreme)', 'https://ffxiv.gamerescape.com/w/images/7/74/Hallowed_Kamuy_%28Mount%29_Icon.png'),
('Hybodus', 'No More Fish In the Sea II', 'https://ffxiv.gamerescape.com/w/images/b/b5/Hybodus_%28Mount%29_Icon.png'),
('Incitatus', '600 Faux Leaves', 'https://ffxiv.gamerescape.com/w/images/9/96/Incitatus_%28Mount%29_Icon.png'),
('Innocent Gwiber', 'The Crown of The Immaculate (Extreme)', 'https://ffxiv.gamerescape.com/w/images/2/2d/Innocent_Gwiber_%28Mount%29_Icon.png'),
('Ironfrog Mover', 'Fathard - Eulmore - 12 Formidable Cog (FATE "A Finale Most Formidable")', 'https://ffxiv.gamerescape.com/w/images/b/b8/Ironfrog_Mover_%28Mount%29_Icon.png'),
('Ixion', '400 Faux Leaves', 'https://ffxiv.gamerescape.com/w/images/7/7b/Ixion_%28Mount%29_Icon.png'),
('Jibanyan Couch', 'Yo-kai Watch Collaboration', 'https://ffxiv.gamerescape.com/w/images/4/4b/Jibanyan_Couch_%28Mount%29_Icon.png'),
('Juedi', 'Dressed for Heaven', 'https://ffxiv.gamerescape.com/w/images/3/39/Juedi_%28Mount%29_Icon.png'),
('Kamuy of The Nine Tails', 'A Lone Wolf No More', 'https://ffxiv.gamerescape.com/w/images/c/c5/Kamuy_of_the_Nine_Tails_%28Mount%29_Icon.png'),
('Kingly Peacock', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/5/54/Kingly_Peacock_%28Mount%29_Icon.png'),
('Kirin', 'A Legend For a Legend', 'https://ffxiv.gamerescape.com/w/images/e/e4/Kirin_%28Mount%29_Icon.png'),
('Kongamato', 'Vath Stickpeddler - Loth ast Vath - 200,000 Gil', 'https://ffxiv.gamerescape.com/w/images/e/ef/Kongamato_%28Mount%29_Icon.png'),
('Korpokkur Kolossus', '750,000 MGP', 'https://ffxiv.gamerescape.com/w/images/f/f2/Korpokkur_Kolossus_%28Mount%29_Icon.png'),
('Laurel Goobbue', 'Sylphic Vendor - Little Solace - 120,000 Gil', 'https://ffxiv.gamerescape.com/w/images/7/77/Laurel_Goobbue_%28Mount%29_Icon.png'),
('Legacy Chocobo', 'Legacy Campaign', 'https://ffxiv.gamerescape.com/w/images/e/ee/Legacy_Chocobo_%28Mount%29_Icon.png'),
('Legendary Kamuy', 'The Minstrel''s Ballad: Shinryu''s Domain', 'https://ffxiv.gamerescape.com/w/images/a/ac/Legendary_Kamuy_%28Mount%29_Icon.png'),
('Logistics System', 'Behind Enemy Lines I', 'https://ffxiv.gamerescape.com/w/images/6/60/Logistics_System_%28Mount%29_Icon.png'),
('Lone Faehound', 'The Feast: Season 4', 'https://ffxiv.gamerescape.com/w/images/1/1c/Lone_Faehound_%28Mount%29_Icon.png'),
('Lone Hellhoud', 'The Feast: Season 3', 'https://ffxiv.gamerescape.com/w/images/0/04/Lone_Hellhound_%28Mount%29_Icon.png'),
('Lunar Kamuy', 'The Minstrel''s Ballad: Tsukuyomi''s Pain', 'https://ffxiv.gamerescape.com/w/images/8/80/Lunar_Kamuy_%28Mount%29_Icon.png'),
('Magicked Bed', 'Crafted by Carpenter', 'https://ffxiv.gamerescape.com/w/images/8/80/Lunar_Kamuy_%28Mount%29_Icon.png'),
('Magicked Carpet', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/e/e2/Magicked_Carpet_%28Mount%29_Icon.png'),
('Magitek Armor', 'The Ultimate Weapon', 'https://ffxiv.gamerescape.com/w/images/7/7c/Magitek_Avenger_%28Mount%29_Icon.png'),
('Magitek Avenger', 'Die Another Day III', 'https://ffxiv.gamerescape.com/w/images/7/7c/Magitek_Avenger_%28Mount%29_Icon.png'),
('Magitek Avenger A-1', 'Out of Hiding', 'https://ffxiv.gamerescape.com/w/images/4/4b/Magitek_Avenger_A-1_%28Mount%29_Icon.png'),
('Magitek Conveyor', 'The Feast: Season 7', 'https://ffxiv.gamerescape.com/w/images/a/ad/Magitek_Conveyor_%28Mount%29_Icon.png'),
('Magitek Death Claw', 'Jonathas - Old Gridania - 6 Achievement Certificates', 'https://ffxiv.gamerescape.com/w/images/b/b8/Magitek_Death_Claw_%28Mount%29_Icon.png'),
('Magitek Hyperconveyor', 'The Feast: Season 16', 'https://ffxiv.gamerescape.com/w/images/9/96/Magitek_Hyperconveyor_%28Mount%29_Icon.png'),
('Magitek Predator', 'Ala Mhigo', 'https://ffxiv.gamerescape.com/w/images/4/43/Magitek_Predator_%28Mount%29_Icon.png'),
('Magitek Sky Armor', '20,000 Wolf Marks', 'https://ffxiv.gamerescape.com/w/images/7/76/Magitek_Sky_Armor_%28Mount%29_Icon.png'),
('Magna Roader', 'The Feast: Season 11', 'https://ffxiv.gamerescape.com/w/images/4/47/Magna_Roader_%28Mount%29_Icon.png'),
('Manacutter', 'Into the Aery', 'https://ffxiv.gamerescape.com/w/images/1/19/Manacutter_%28Mount%29_Icon.png'),
('Managarm', 'Calamity Salvager - 8 Gold Chocobo Feathers (Recruit a Friend Campaign)', 'https://ffxiv.gamerescape.com/w/images/4/48/Managarm_%28Mount%29_Icon.png'),
('Marid', 'Madhura - Castellum Velodyna - 18 Ananta Dreamstaffs', 'https://ffxiv.gamerescape.com/w/images/9/95/Marid_%28Mount%29_Icon.png'),
('Markab', 'The Striking Tree (Extreme)', 'https://ffxiv.gamerescape.com/w/images/a/ac/Markab_%28Mount%29_Icon.png'),
('Maxima Roader', 'The Feast: Season 12', 'https://ffxiv.gamerescape.com/w/images/5/50/Maxima_Roader_%28Mount%29_Icon.png'),
('Megalotragus', '8,400 Skybuilders'' Scrips', 'https://ffxiv.gamerescape.com/w/images/4/4c/Megalotragus_%28Mount%29_Icon.png'),
('Menoetius', 'The Feast: Season 15', 'https://ffxiv.gamerescape.com/w/images/a/a9/Menoetius_%28Mount%29_Icon.png'),
('Migardsormr', 'Fetters of Lament', 'https://ffxiv.gamerescape.com/w/images/d/d9/Midgardsormr_%28Mount%29_Icon.png'),
('Mikoshi', 'Gyosho - Dhoro Iloh - 20 Namazu Koban', 'https://ffxiv.gamerescape.com/w/images/0/00/Mikoshi_%28Mount%29_Icon.png'),
('Model O', 'Alphascape V4.0 (Savage)', 'https://ffxiv.gamerescape.com/w/images/d/d0/Model_O_%28Mount%29_Icon.png'),
('Morbol', 'True Blue', 'https://ffxiv.gamerescape.com/w/images/3/31/Morbol_%28Mount%29_Icon.png'),
('Mystic Panda', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/d/d0/Mystic_Panda_%28Mount%29_Icon.png'),
('Lunar Whale', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/5/5d/Lunar_Whale_%28Mount%29_Icon.png'),
('Polar Bear', 'A Treat to Beat The Heat', 'https://ffxiv.gamerescape.com/w/images/2/2a/Polar_Bear_%28Mount%29_Icon.png'),
('Nezha Chariot', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/2/20/Nezha_Chariot_%28Mount%29_Icon.png'),
('Nightmare', 'Ifrit, Garuda, Titan (Extreme Versions)', 'https://ffxiv.gamerescape.com/w/images/3/36/Nightmare_%28Mount%29_Icon.png'),
('Original Fat Chocobo', 'In-Game Item Campaign', 'https://ffxiv.gamerescape.com/w/images/d/df/Original_Fat_Chocobo_%28Mount%29_Icon.png'),
('Pack Faehound', 'The Feast: Season 4', 'https://ffxiv.gamerescape.com/w/images/e/e3/Pack_Faehound_%28Mount%29_Icon.png'),
('Pack Hellhound', 'The Feast: Season 3', 'https://ffxiv.gamerescape.com/w/images/b/ba/Pack_Hellhound_%28Mount%29_Icon.png'),
('Parade Chocobo', 'Leaving a Better Impression II', 'https://ffxiv.gamerescape.com/w/images/b/bf/Parade_Chocobo_%28Mount%29_Icon.png'),
('Pegasus', '4200 Skybuilders'' Scrips', 'https://ffxiv.gamerescape.com/w/images/0/0d/Pegasus_%28Mount%29_Icon.png'),
('Portly Porxie', 'Jul Oul - Il Mheg - 18 Fae Fancy', 'https://ffxiv.gamerescape.com/w/images/c/cd/Portly_Porxie_%28Mount%29_Icon.png'),
('Prototype Conveyor', 'The Feast: Season 8', 'https://ffxiv.gamerescape.com/w/images/3/38/Prototype_Conveyor_%28Mount%29_Icon.png'),
('Prototype Roader', 'The Feast: Season 17', 'https://ffxiv.gamerescape.com/w/images/d/d9/Prototype_Roader_%28Mount%29_Icon.png'),
('Pteranodon', 'Castle In The Sky', 'https://ffxiv.gamerescape.com/w/images/2/2b/Pteranodon_%28Mount%29_Icon.png'),
('Raigo', 'Furious Fatalities', 'https://ffxiv.gamerescape.com/w/images/d/dc/Raigo_%28Mount%29_Icon.png'),
('Ramuh', 'Eden''s Verse: Refulgence (Savage)', 'https://ffxiv.gamerescape.com/w/images/6/6f/Ramuh_%28Mount%29_Icon.png'),
('Rathalos', 'The Great Hunt (Extreme)', 'https://ffxiv.gamerescape.com/w/images/0/02/Rathalos_%28Mount%29_Icon.png'),
('Red Baron', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/c/c3/Red_Baron_%28Mount%29_Icon.png'),
('Red Hare', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/4/47/Red_Hare_%28Mount%29_Icon.png'),
('Reveling Kamuy', 'The Pool of Tribute (Extreme)', 'https://ffxiv.gamerescape.com/w/images/3/39/Reveling_Kamuy_%28Mount%29_Icon.png'),
('Rolling Tankard', '18 Hammered Frogments', 'https://ffxiv.gamerescape.com/w/images/9/9c/Rolling_Tankard_%28Mount%29_Icon.png'),
('Rose Lanner', 'Thok ast Thok', 'https://ffxiv.gamerescape.com/w/images/c/c4/Rose_Lanner_%28Mount%29_Icon.png'),
('Round Lanner', 'The Minstrel''s Ballad: Thordan''s Reign', 'https://ffxiv.gamerescape.com/w/images/e/e7/Round_Lanner_%28Mount%29_Icon.png'),
('Rubellite Carbancle', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/e/e3/Rubellite_Carbuncle_%28Mount%29_Icon.png'),
('Ruby Gwiber', 'Cinder Drift (Extreme)', 'https://ffxiv.gamerescape.com/w/images/4/44/Ruby_Gwiber_%28Mount%29_Icon.png'),
('Sabotender Emperador', '2,000,000 MGP', 'https://ffxiv.gamerescape.com/w/images/6/63/Sabotender_Emperador_%28Mount%29_Icon.png'),
('Safe Guard System', 'Front and Center', 'https://ffxiv.gamerescape.com/w/images/b/bb/Safeguard_System_%28Mount%29_Icon.png'),
('Sanuwa', 'Luna Vanu - Ok'' Gundu Nakki - 200,000 Gil', 'https://ffxiv.gamerescape.com/w/images/0/06/Sanuwa_%28Mount%29_Icon.png'),
('SDS Fenrir', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/4/41/SDS_Fenrir_%28Mount%29_Icon.png'),
('Serpent Warsteed', 'A Line in the Glade IV', 'https://ffxiv.gamerescape.com/w/images/2/2e/Serpent_Warsteed_%28Mount%29_Icon.png'),
('Shadow Gwiber', 'The Minstrel''s Ballad: Hades''s Elegy', 'https://ffxiv.gamerescape.com/w/images/0/0e/Shadow_Gwiber_%28Mount%29_Icon.png'),
('Sleipnir', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/5/5a/Sleipnir_%28Mount%29_Icon.png'),
('Snowman', 'Starlight Celebration (2020)', 'https://ffxiv.gamerescape.com/w/images/b/b9/Snowman_%28Mount%29_Icon.png'),
('Sophic Lanner', '	Containment Bay P1T6 (Extreme)', 'https://ffxiv.gamerescape.com/w/images/e/e4/Sophic_Lanner_%28Mount%29_Icon.png'),
('Spriggan Stonecarrier', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/6/64/Spriggan_Stonecarrier_%28Mount%29_Icon.png'),
('Starlight Bear', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/7/76/Starlight_Bear_%28Mount%29_Icon.png'),
('Storm Warsteed', 'A Line in the Storm IV', 'https://ffxiv.gamerescape.com/w/images/9/98/Storm_Warsteed_%28Mount%29_Icon.png'),
('Striped Ray', 'Shikitahe - Tamamizu - 12 Kojin Sango', 'https://ffxiv.gamerescape.com/w/images/0/00/Striped_Ray_%28Mount%29_Icon.png'),
('Sunspun Cumulus', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/9/92/Sunspun_Cumulus_%28Mount%29_Icon.png'),
('Syldra', 'Stormblood Collector''s Edition', 'https://ffxiv.gamerescape.com/w/images/b/b3/Syldra_%28Mount%29_Icon.png'),
('Triceratops', 'Nuts for Nutsy', 'https://ffxiv.gamerescape.com/w/images/1/13/Triceratops_%28Mount%29_Icon.png'),
('True Griffin', 'Madhura - Castellum Velodyna - 18 Ananta Dreamstaffs', 'https://ffxiv.gamerescape.com/w/images/c/c7/True_Griffin_%28Mount%29_Icon.png'),
('Twintania', 'Calamity Salvager - 15 Gold Chocobo Feathers (Recruit a Friend Campaign)', 'https://ffxiv.gamerescape.com/w/images/c/c5/Twintania_%28Mount%29_Icon.png'),
('Typhon', '750,000 MGP', 'https://ffxiv.gamerescape.com/w/images/e/e5/Typhon_%28Mount%29_Icon.png'),
('Tyrannosaur', 'Anemos Lockbox', 'https://ffxiv.gamerescape.com/w/images/b/bb/Tyrannosaur_%28Mount%29_Icon.png'),
('Ufiti', '8,400 Skybuilders'' Scrips', 'https://ffxiv.gamerescape.com/w/images/0/0a/Ufiti_%28Mount%29_Icon.png'),
('Unicorn', 'Unicorn Power', 'https://ffxiv.gamerescape.com/w/images/6/6a/Unicorn_%28Mount%29_Icon.png'),
('War Panther', 'But Somebody''s Gotta Do It (Dark Knight)', 'https://ffxiv.gamerescape.com/w/images/9/97/War_Panther_%28Mount%29_Icon.png'),
('War Tiger', 'Tank You, Gunbreaker II', 'https://ffxiv.gamerescape.com/w/images/1/1f/War_Tiger_%28Mount%29_Icon.png'),
('Warbear', 'But Somebody''s Gotta Do It (Warrior)', 'https://ffxiv.gamerescape.com/w/images/8/84/Warbear_%28Mount%29_Icon.png'),
('Warlion', 'But Somebody''s Gotta Do It (Paladin', 'https://ffxiv.gamerescape.com/w/images/9/9b/Warlion_%28Mount%29_Icon.png'),
('Warring Lanner', '	Containment Bay S1T7 (Extreme)', 'https://ffxiv.gamerescape.com/w/images/1/13/Warring_Lanner_%28Mount%29_Icon.png'),
('Whisper-go', 'Yo-kai Watch Collaboration', 'https://ffxiv.gamerescape.com/w/images/4/47/Whisper-go_%28Mount%29_Icon.png'),
('White Devil', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/2/26/White_Devil_%28Mount%29_Icon.png'),
('White Lanner', 'The Limitless Blue (Extreme)', 'https://ffxiv.gamerescape.com/w/images/8/85/White_Lanner_%28Mount%29_Icon.png'),
('Witch''s Broom', 'Mogstation', 'https://ffxiv.gamerescape.com/w/images/1/1a/Witch%27s_Broom_%28Mount%29_Icon.png'),
('Wyvern', 'Bertana - Idyllshire - 6 Clan Mark Logs', 'https://ffxiv.gamerescape.com/w/images/7/7f/Wyvern_%28Mount%29_Icon.png'),
('Xanthos', 'The Howling Eye (Extreme)', 'https://ffxiv.gamerescape.com/w/images/b/bc/Xanthos_%28Mount%29_Icon.png'),
('Yol', 'In the Footsteps of Bardam the Brave', 'https://ffxiv.gamerescape.com/w/images/b/b5/Yol_%28Mount%29_Icon.png'),
('Zu', 'Spoils Collector - 1 Iron Voyage Spoil (from sector Sea of Clouds 24)', 'https://ffxiv.gamerescape.com/w/images/e/e8/Zu_%28Mount%29_Icon.png');

-- ('Al-iklil', 'A Complete History', 'https://ffxivcollect.com/assets/blank-02e0f108cbc50a054e34fe367afc0ef110e7aab768097e9baaad8453270c37b1.png'),